defaults: &defaults
  box: "maier/alpine-3.4-x86_64"
  ram: 512
  gui: false
  cpus: 1
  provider: "virtualbox"
  vtx: "on"
  maxcpu: 50
  apic: "on"
  guestext: false
  vboxsf: false
  provisioning: |
    #!/bin/bash
    apk update && apk add ansible
    wget -O/tmp/inventory.ini http://raw.githubcontent.com/denzuko/
    wget -O/tmp/provisioning.yml http://raw.githubcontent.com/denzuko/
    sudo ansible-playbook -i /tmp/inventory.ini /tmp/provisioning.yml)

develop: 
  <<: *defaults
  vtx: "on"

testing: 
  <<: *defaults
  vtx: "on"

staging:
  <<: *defaults

production:
  <<: *defaults
